apiVersion: apps/v1
kind: Deployment
metadata:
  name: sub-backend
spec:
  replicas: 2
  template:
    metadata:
      name: sub-backend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - sub-backend
            topologyKey: kubernetes.io/hostname
      containers:
        - name: sub-backend
          resources:
            requests:
              memory: "300Mi"
              cpu: "200m"
            limits:
              memory: "750Mi"
              cpu: "1"            
