---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sub-backend-env
data:
  CORS_ALLOWED_ORIGIN: "*"
  EMAIL_FROM: ""
  EMAIL_HOST: ""
  EMAIL_PASSWORD: ""
  EMAIL_PORT: "465"
  EMAIL_USER: ""
  ES_NODE_URL: https://10.110.0.2:9200
  ES_OFFCHAIN_USER: elastic
  ES_READONLY_USER: elastic
  FAUCET_DRIP_AMOUNT: "0.05"
  FAUCET_MAX_AMOUNT_TOP_UP: "0.025"
  FAUCET_MNEMONIC: ""
  IPFS_CLUSTER_URL: https://test-pin.crustcloud.io/psa
  IPFS_GATEWAY_URL: https://ipfs.subsocial.network
  IPFS_MAX_FILE_SIZE_BYTES: "2097152"
  IPFS_NODE_URL: https://gw-seattle.crustcloud.io
  IPFS_READ_ONLY_NODE_URL: https://ipfs.subsocial.network
  IPFS_CRUST_AUTH: eyJkYXRhIjp7ImRvbWFpbiI6eyJjaGFpbklkIjoiNSIsIm5hbWUiOiJDbG91ZDMuY2MiLCJ2ZXJpZnlpbmdDb250cmFjdCI6IjB4Q2NDQ2NjY2NDQ0NDY0NDQ0NDQ2NDY0NjY0NjQ0NDY0NjY2NjY2NjQyIsInZlcnNpb24iOiIxIn0sIm1lc3NhZ2UiOnsiZGVzY3JpcHRpb24iOiJTaWduIGZvciBXMyBCdWNrZXQgQWNjZXNzIEF1dGhlbnRpY2F0aW9uIiwic2lnbmluZ0FkZHJlc3MiOiIweDAwNDFjNzA1ZTEwNmVlOWRFMjI3Q2ExMzlBZDRBOTlEQjY0NENCM2EiLCJ0b2tlbkFkZHJlc3MiOiIweDM5ODY2Mzg0MjY4MDMzMkExQWJBM0IwM2JkNmRCNDdhRTk4NDk5NEMiLCJ0b2tlbklkIjoiMzAwMDAzNyIsImVmZmVjdGl2ZVRpbWVzdGFtcCI6MTY3ODUzNzYxNywiZXhwaXJhdGlvblRpbWVzdGFtcCI6MH0sInByaW1hcnlUeXBlIjoiVzNCdWNrZXQiLCJ0eXBlcyI6eyJXM0J1Y2tldCI6W3sibmFtZSI6ImRlc2NyaXB0aW9uIiwidHlwZSI6InN0cmluZyJ9LHsibmFtZSI6InNpZ25pbmdBZGRyZXNzIiwidHlwZSI6ImFkZHJlc3MifSx7Im5hbWUiOiJ0b2tlbkFkZHJlc3MiLCJ0eXBlIjoiYWRkcmVzcyJ9LHsibmFtZSI6InRva2VuSWQiLCJ0eXBlIjoic3RyaW5nIn0seyJuYW1lIjoiZWZmZWN0aXZlVGltZXN0YW1wIiwidHlwZSI6InVpbnQyNTYifSx7Im5hbWUiOiJleHBpcmF0aW9uVGltZXN0YW1wIiwidHlwZSI6InVpbnQyNTYifV19fSwic2lnbmF0dXJlIjoiMHhhMTUxODkyZGNhMTZlMTJkZmViYTFjY2FkMjNmZjM5MGVmODQ1MzdhMGI2MWI4YWQ1NDY1ZGI1ZjI1NjZkMWJmMjc3MGE1OTQyMzFmNzFmYzA5YWVlZGJhNzJkZjM5Y2Y4NDIxMTQ3YzJkNWQyNTFkNDZjNGQyMDFlOGM1MmUzZTFjIn0=
  KUSAMA_NODE_URL: wss://kusama-rpc.polkadot.io
  LOG_LEVEL: info
  MAX_RESULTS_LIMIT: "20"
  OFFCHAIN_REQ_TIMEOUT_SECS: "60"
  OFFCHAIN_SERVER_PORT: "3001"
  OFFCHAIN_TELEGRAM_WS_PORT: "3020"
  OFFCHAIN_WS_PORT: "3011"
  PG_SSL: "false"
  PGDATABASE: subsocial_offchain
  PGHOST: 10.110.0.2
  PGPORT: "5432"
  PGUSER: subsocial_offchain_usr
  PG_MAX_POOL_SIZE: "100"
  RECAPTCHA_KEY: ""
  SUBSTRATE_EVENT_METHODS: SpaceCreated,SpaceUpdated,SpaceFollowed,SpaceUnfollowed,AccountFollowed,AccountUnfollowed,PostCreated,PostUpdated,PostShared,CommentCreated,CommentUpdated,PostReactionCreated,CommentReactionCreated,ProfileCreated
  SUBSTRATE_EVENT_SECTIONS: permissions,posts,profileFollows,profiles,reactions,scores,spaceFollows,spaceOwnership,spaces,utils
  SUBSTRATE_URL: wss://testnet.subsocial.network
  TEST_MODE: "false"
